version: 2.1
orbs:
  ssh: skillup/ssh@2.1.0

jobs: 
  build: 
    working_directory: /usr/src/app
    docker:
      - image: velink/interview-nodeapp:0.0.2
    steps: 
      - checkout
      - run: npm start
  test: 
    working_directory: /usr/src/app
    docker: 
      - image: velink/interview-nodeapp:0.0.2
    steps: 
      - checkout 
      - run: npm test
  deploy:
    working_directory: /usr/src/app
    docker: 
      - image: velink/interview-nodeapp:0.0.2
    steps:
        - add_ssh_keys:
            fingerprints:
               - "b7:35:a6:4e:9b:0d:6d:d4:78:1e:9a:97:2a:66:6b:be"
        - run: 
           name: Deploy over SSH
           command:  |
             ssh -o StrictHostKeyCheckin=no ubuntu@18.170.99.114 
             echo "we get to here"

# Invoke jobs via worklow 
workflows: 
  build:
    jobs:
     - build
     - test:
         requires:
         - build
     - deploy:
         requires:
         - build 