version: 2.1

jobs: 
  build: 
    working_directory: /usr/src/app
    docker:
      - image: velink/interview-nodeapp:0.0.1
    steps: 
      - checkout
      - run: npm start

# Invoke jobs via worklow 
workflows: 
  build:
    jobs:
     - build