---

version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@8.1.3 
  aws-ecs: circleci/aws-ecs@3.2.0
  github-super-linter: circleci/github-super-linter@1.0.1

jobs: 
  unit_tests:
    working_directory: /usr/src/app
    docker:
      - image: 776933909252.dkr.ecr.eu-west-2.amazonaws.com/interview-nodeapp:'$CIRCLE_SHA1'
        aws_auth:
          aws_access_key_id: $AWS_ACCESS_KEY_ID
          aws_secret_access_key: $AWS_SECRET_ACCESS_KEY
    steps: 
      - checkout
      - run: npm test

# Invoke jobs via worklow 
# Testing filter to main

workflows:
  build_and_push_image:
    jobs:
      - github-super-linter/lint
      - aws-ecr/build-and-push-image:
          requires:
            - github-super-linter/lint
          repo: interview-nodeapp
          dockerfile: dockerfile
          path: .
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          region: eu-west-2
          registry-id: AWS_ECR_REGISTRY_ID
          tag: '$CIRCLE_SHA1'
      - unit_tests: 
          requires:
            - aws-ecr/build-and-push-image
      - aws-ecs/deploy-service-update:
          requires:
            - unit_tests
          family: interview-nodeapp
          cluster: interview-nodeapp
          container-image-name-updates: "container=interview-nodeapp,tag=$CIRCLE_SHA1"
          filters:
            branches:
              only:
                - main


  # PULLING IMAGE FROM DOCKER REGISTRY 
  # build: 
  #   working_directory: /usr/src/app
  #   docker:
  #     - image: velink/interview-nodeapp:0.0.2
  #   steps: 
  #     - checkout
  #     - run: npm start
  # test: 
  #   working_directory: /usr/src/app
  #   docker: 
  #     - image: velink/interview-nodeapp:0.0.2
  #   steps: 
  #     - checkout 
  #     - run: npm test
     
# workflows: 
#   build:
#     jobs:
#      - build
#      - test:
#          requires:
#          - build
#      - deploy:
#          requires:
#          - build 