version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@8.1.3 

jobs: 
  build: 
    working_directory: /usr/src/app
    docker:
      - image: velink/interview-nodeapp:0.0.2
    steps: 
      - checkout
      - run: npm start
  test: 
    working_directory: /usr/src/app
    docker: 
      - image: velink/interview-nodeapp:0.0.2
    steps: 
      - checkout 
      - run: npm test


# Invoke jobs via worklow 

workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build-and-push-image:
          repo: interview-nodeapp
          tag: "latest, v0.1.${CIRCLE_BUILD_NUM}"
          dockerfile: dockerfile
          path: .
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          region: $AWS_REGION
          registry-id: "776933909252"
     
# workflows: 
#   build:
#     jobs:
#      - build
#      - test:
#          requires:
#          - build
#      - deploy:
#          requires:
#          - build 