version: 2.1

jobs: 
  build: 
    working_directory: /usr/src/app
    docker:
      - image: velink/interview-nodeapp:0.0.2
    steps: 
      - checkout
      - run: npm start
  test: 
    working_directory: /usr/src/app
    docker: 
      - image: velink/interview-nodeapp:0.0.2
    steps: 
      - checkout 
      - run: npm test
  deploy:
    working_directory: /usr/src/app
    docker: 
      - image: velink/interview-nodeapp:0.0.2
    steps:
        - run: 
           name: Deploy over SSH
           command: |
           ssh ubuntu@18.170.99.114 

# Invoke jobs via worklow 
workflows: 
  build:
    jobs:
     - build
     - test:
         requires:
         - build
     - deploy:
         requires:
         - build 